### ISSUE TITLE
iCloud Photos "update" action needed before calling photos.all()

### ISSUE THREAD

**Issue by jake-b** [picklepete/pyicloud#85]
I noticed that the photos.all() function was not returning some recent photos in my library.

After logging into icloud.com and clicking the "update" button at the bottom of the photo library (the text that says "xxxx photos and videos; last updated yyyy")  The recent photos appeared in my library and were then available to photos.all()

Took some time trying to figure out what's going on in the javascript debugger, but this isn't really my area of expertise, and I didn't make any progress.

Consider this a feature request to add a "update()" action to the photos service so that the library can be synched prior to calling photos.all()

Thanks for your efforts.

**Comment by torarnv** [comment]
I have a branch that implements this. Will clean it up and push it.

**Comment by chrismetcalf** [comment]
Thanks @torarnv! I'm seeing this too, and would love to see that fix pushed out, or a link to the branch so that I can try it out. Trying to get https://github.com/ndbroadbent/icloud_photos_downloader working.

**Comment by jake-b** [comment]
@torarnv thank you!

@chrismetcalf yeah, I'm using that script as well, packaged as a Docker container on my NAS.  Need the ability to update the library in order to fully automate the iCloud backup process.

**Comment by torarnv** [comment]
I've pushed a somewhat cleaned up version to [wip/photos-update]( https://github.com/torarnv/pyicloud/tree/wip/photos-update). I'm going on vacation now for four weeks, but I thought you guys might want to test it a bit. I'll finish up the patch, with docs, and push a PR once I get back.

**Comment by jake-b** [comment]
I've been playing with it.  I did get one error early on, but I haven't been able to reproduce it yet:

```  File "/pyicloud/pyicloud/services/photos.py", line 156, in update
    album = self._photo_albums[server_id]
KeyError: u'all-photos'```

Still more testing to do.

**Comment by chadj** [comment]
@jake-b I've been able to reproduce that error on this [wip/photos-update](https://github.com/torarnv/pyicloud/tree/wip/photos-update) branch.  If `PhotosService.update` is called before `PhotosService._photo_albums` is populated and a new asset is found then this error is thrown.

**Comment by chadj** [comment]
I found another issue that can occur when calling `PhotosService.update` and a delete is found but the corresponding asset doesn't exist in the local data structures.  Pull request torarnv/pyicloud#1 attempts to fix that.

**Comment by chrismetcalf** [comment]
Any updates on this fix?

**Comment by torarnv** [comment]
Sorry guys, Ive been a bit swamped. Will try to finish this this week or next.

**Comment by knorrie** [comment]
I just tested the wip/photos-update branch, with the KeyError: u'all-photos' fix from chadj on top, and was successfully able to retrieve a new photo that I just made by first calling icloud.photos.update() before doing something with icloud.photos.all.

Without these fixes, I had to log in to icloud in the webbrowser first and visit photos to get the index updated, after which it would retrieve the new photo.

**Comment by torarnv** [comment]
Pushed a PR, please test 😄

**Comment by bobhavlin** [comment]
I am unable to get the api.photos.update() to actually update the photos file list.

```
pip install git+https://github.com/torarnv/pyicloud.git@photos-update
$ python
Python 2.7.12 (default, Oct 10 2016, 12:50:22) 
>>> from pyicloud import PyiCloudService
>>> api = PyiCloudService('myemail@gmail.com')
>>> api.photos.update()
True
>>> api.photos.update()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pyicloud/services/photos.py", line 177, in update
    del album.photos[index]
IndexError: list assignment index out of range
>>> api.photos.update()
True
```
`for photo in api.photos.all: ...`
Then, when I iterate through the files the new ones are still not available until I login through a browser at icloud.com

Am I missing something here or does _api.photos.update()_ not work as expected?

**Comment by torarnv** [comment]
Thanks for the feedback @bobhavlin, what kind of updates did you do between the updates?

**Comment by chadj** [comment]
If I'm not mistaken it looks like the contents of this pull request torarnv/pyicloud#1 didn't make it into this pull request picklepete/pyicloud#100 .

**Comment by bobhavlin** [comment]
@torarnv , I did nothing between the _api.photos.updates()_ not really sure why there was an error...  I just tried it multiple times within approx 30 sec to see if it might update the new photos.

**Comment by bobhavlin** [comment]
Not sure if this helps, but tried enabling DEBUG:

```
...
2016-10-18 11:47:33,411 - pyicloud.services.photos - INFO - Looking for photo library changes...
2016-10-18 11:47:33,411 - pyicloud.services.photos - INFO - No albums fetched yet, doing full update
2016-10-18 11:47:33,411 - pyicloud.services.photos - DEBUG - Fetching folders ...
2016-10-18 11:47:33,413 - pyicloud.services.photos.http - DEBUG - GET https://p04-photosws.icloud.com:443/ph/folders None
2016-10-18 11:47:33,804 - requests.packages.urllib3.connectionpool - DEBUG - "GET /ph/folders?clientBuildNumber=14E45&clientInstanceId=8F895094-9552-11E6-B99B-00FF82E11130&dsid=116449392&syncToken=AQAABAAGe3f%2F%2F%2F%2F%2F%2F%2F%2F%2F%2Fd8P5GPJTNU30gHlIh-3 HTTP/1.1" 200 None
2016-10-18 11:47:33,809 - pyicloud.services.photos.http - DEBUG - {u'folders': [{u'isServerGenerated': True, u'contentsType': u'folder', u'type': u'folder', u'serverId': u'top-level-generated', u'childFolderIds': 
...
```

**Comment by torarnv** [comment]
@chadj The check was added a bit further up:
```py
if server_id not in self._photo_albums:
    logger.warning("Album %s was not fetched yet",
                   server_id)
    updated_folders.append(server_id)
    continue
```

@bobhavlin: The iCloud servers will not always report back any changes even if you call `update()`, so you need to call it in a loop yourself, with some reasonable rate-limit.

**Comment by torarnv** [comment]
@bobhavlin: The exception you're seeing is of course an issue, but I'd like to understand why we'd end up in that situation in the first place.

I've wrapped the same logic for `folder` changes in a check for `server_id` on remove, with a warning, so we could do that here too, but it's a symptom of a missing update that we never saw.

**Comment by torarnv** [comment]
I've updated PR #100, please pull and then try calling `api.photos.update()` in a loop, every 1 minute, with DEBUG enabled, while doing changes in your photo albums. Let's weed out any issues :smiley:

**Comment by bobhavlin** [comment]
@torarnv Are there changes from _pip install git+https://github.com/torarnv/pyicloud.git@photos-update_ you want to test?

I was doing interactive testing and noticed that sometimes from the above pull that sometimes it would update the photos index and sometimes not.  Sometimes even after logging into icloud.com the files would not appear in the index, then I would try again a few minutes later and they would appear.

**Comment by torarnv** [comment]
@bobhavlin I can reproduce the issue locally, so no need to test for now.

If you enable DEBUG you can watch the replies iCloud gives us for the update action. If they are empty there's not much we can do.

**Comment by apjithesh** [comment]
Hi, I had tried this late nov and it all worked fine, and I setup a cron as well, but when i checked recently I see that it is not downloading any new photos, i logged into icloud and over there i see it has 681 but when i run the py script after logging into icloud, it still shows 619 and does not download any.... I was thinking this update() script would help, but I dont think it is related to this as it is not getting refreshed with the list even if i logged into icloud.

I used this script - https://github.com/ndbroadbent/icloud_photos_downloader, but to test eliminating this script I tried direct using the command line from readme of this module itself, still was giving the size as 619. Any help or direction will be really helpful (apologies if this was not the right place, but i thought it was related)

**Comment by chipturner** [comment]
I am experiencing this issue as well; is there anything blocking this?  Any further testing or assistance needed to get the update action available to pyicloud?  I also am trying to automate my backups and this is the last hurdle.

**Comment by torarnv** [comment]
I've limited #100 in scope to doing full updates of the service when updates are detected. Please test.

**Comment by Thamster** [comment]
Still not seeing all latest photos when using the PhotoService api...

**Comment by Thamster** [comment]
Still not retrieving all the latest photos and videos for some reason. They are clearly visible on icloud.com and using the icloud for windows downloader, using pyicloud there are a couple of months of images missing.

**Comment by cvpe** [comment]
I had the same problem but I've added in pyicloud/services/Photos,py, in the class PhotoService, The update def of torarnv and it's ok now, Thanks to him

**Comment by Thamster** [comment]
wow ok thanks, I cloned the latest

`git clone https://github.com/picklepete/pyicloud`

then replaced photos.py with 

`wget https://raw.githubusercontent.com/torarnv/pyicloud/10ae037cc0a123b87ee2077cadd78ffe088e9c09/pyicloud/services/photos.py`

and did 

`python setup.py install`

and we are back in business.

**Comment by cvpe** [comment]
I'm happy for you but you have to thanks @torarnv not me...

**Comment by cvpe** [comment]
@torarnv I've the same kind of problem when I try to download a file from iCloud Drive.
I get an obsolete version of the file! 
Is it possible to have a sort of update like you did for photos?
Thanks

**Comment by torarnv** [comment]
@cvpe please open a new bug report for other part of the API, so we can keep the conversation about the Photos service focused.

**Comment by cvpe** [comment]
Hello
Sorry to annoy you (and sorry for my poor English).
But I had already opened a new issue with this problem of obsolete/old files.
If I put this comment in "your" issue about photos, it's only to ask you (who solved the problem of obsolete photos) if you don't have a way to perform the same kind of process on files.
Thank you

**Comment by torarnv** [comment]
@cvpe I realize your intent, but by doing so you are adding noise to *this* issue, making it less likely that it will be resolved. For the future (both for this project and others) a better approach would be to reference this bug *from* the other bug, or ping me in *the other bug*. Thanks!

**Comment by cvpe** [comment]
One more time, sorry. I am really not used with GitHub.
I put a comment in the other issue pointing to this one, hoping it's what you hoped.
The real problem is that I don't see any reaction of @picklepete to all these issues and I see you're active and that you really solved this problem of photos update...

**Comment by wiswashegrove** [comment]
Hi there,
Hope all are doing great.

I am still facing the same issue even with latest build.
@Thamster I tried as you mentioned in your above comment. But still the old photos.

Am I the only one who is getting this issue now? Really looking forward to hear from any of you.

Thanks a lot for help me out!

**Comment by bobhavlin** [comment]
Works for me with: 
pip install --upgrade git+https://github.com/torarnv/pyicloud.git@photos-update

```
from pyicloud import PyiCloudService
import os, sys, time
import datetime
import os.path

X = -500

dir = "/home/bob/Pictures/icloud-photos-pyq"
api = PyiCloudService('email@mail.com')

#implementing update from: https://github.com/torarnv/pyicloud/tree/photos-update
api.photos.update()

for i in range(X, -1, 1):
   print api.photos.all[i].filename, api.photos.all[i].created
   dtt = api.photos.all[i].created
   dt = datetime.datetime.strptime(dtt, "%Y-%m-%dT%H:%M:%SZ")

   filename, ext = os.path.splitext(api.photos.all[i].filename)
   ts = dt.strftime('%Y%m%d-%H%M%S')
   output_filename = str.format("{0}_{1}{2}", ts, filename, ext)
   output_file = os.path.join(dir, output_filename)
   if os.path.isfile(output_file):
       print "File " + output_filename + " already exists"
       continue
   print "Writing file to " + output_file
   download = api.photos.all[i].download('original');
   with open(output_file, 'wb') as opened_file:
      opened_file.write(download.raw.read())
   if output_file.lower().endswith(('.mov', '.png')):
       os.utime(output_file, (time.mktime(dt.timetuple()),)*2)
```

This is my ugly script to pull my most recent 500 photos everyday.  I'm sure there is huge room for improvement, but works for me.

**Comment by torarnv** [comment]
Please try the latest master, now that https://github.com/picklepete/pyicloud/pull/137 has merged
